### ISSUE TITLE
Trouble installing from Github: 'alevinQC' requires R>= 3.6

### ISSUE THREAD

**Issue by jaclyn-taroni** [csoneson/alevinQC#4]
Hi @csoneson,

Thanks for this package! We were trying to install alevinQC from Github on a Docker image (`rocker/tidyverse:3.5.1`) with the following command: 

```R
devtools::install_github('csoneson/alevinQC', 
                         ref = '39ac022304ff53812e54d03cf4b6a0ab2838fe6a', 
                         dependencies = TRUE)
```

We received this error:

```
Error this R is version '3.5.1' 'alevinQC' requires R>= 3.6
```

I have no experience writing R packages so I may be incorrect, but I believe that this may arise from this line: https://github.com/csoneson/alevinQC/blob/d0ed40d1e49fb8bdfb32945f260f604c03d4cacd/DESCRIPTION#L10

I expect this value should be `3.5` given that the latest R release is `3.5.3`. I can confirm that rolling back to an earlier commit (https://github.com/csoneson/alevinQC/commit/4f9bcbef6a4a60c69572b2928bea65112bb8aeb2) successfully installs.

I realize that the recommended installation method is through the development version of Bioconductor. This may not be an issue for many users, but I wanted to report it.

**Comment by csoneson** [comment]
Dear Jaclyn,
thanks for your message.
In fact, you need R v3.6 (i.e., current R-devel) to run also the current GitHub version of `alevinQC`, since it depends on data import functionality that was introduced in `tximport` v1.11.5 (available in the Bioconductor devel branch, which requires R v3.6). The earlier version of `alevinQC` contained (basically duplicated) this data import functionality, which is why it can be installed into older R versions. 
Best,
Charlotte

**Comment by jaclyn-taroni** [comment]
Gotcha! Thanks for the quick reply. I will close this issue.
